'use strict'
module.exports = [
        0,//"None",
        0,//"Health",
        0,//"Strength",
        0,//"Agility",
        0,//"Intelligence",
        0,//"Speed",
        0,//"Physical Damage",
        0,//"Special Damage", //"UNIT_STAT_ABILITY_POWER",
        0,//"Armor", //"UNIT_STAT_ARMOR",
        0,//"Resistance", //"UNIT_STAT_SUPPRESSION",
        0,//"Armor Penetration", //"UNIT_STAT_ARMOR_PENETRATION",
        0,//"Resistance Penetration", //"UNIT_STAT_SUPPRESSION_PENETRATION",
        0.02,//"Dodge Rating", //"UNIT_STAT_DODGE_RATING",
        0.02,//"Deflection Rating", //"UNIT_STAT_DEFLECTION_RATING",
        0,//"Physical Critical Rating", //"UNIT_STAT_ATTACK_CRITICAL_RATING",
        0,//"Special Critical Rating", //"UNIT_STAT_ABILITY_CRITICAL_RATING",
        1.5,//"Critical Damage",
        0,//"Potency",
        0.15,//"Tenacity",
        0,//"UNIT_STAT_DODGE_PERCENT_ADDITIVE",
        0,//"UNIT_STAT_DEFLECTION_PERCENT_ADDITIVE",
        0.10,//"Physical Critical Chance", //"UNIT_STAT_ATTACK_CRITICAL_PERCENT_ADDITIVE",
        0.10,//"Special Critical Chance", //"UNIT_STAT_ABILITY_CRITICAL_PERCENT_ADDITIVE",
        0,//"UNIT_STAT_ARMOR_PERCENT_ADDITIVE",
        0,//"UNIT_STAT_SUPPRESSION_PERCENT_ADDITIVE",
        0,//"UNIT_STAT_ARMOR_PENETRATION_PERCENT_ADDITIVE",
        0,//"UNIT_STAT_SUPPRESSION_PENETRATION_PERCENT_ADDITIVE",
        0,//"Health Steal",//"UNIT_STAT_HEALTH_STEAL",
        0,//"Protection",
        0,//"UNIT_STAT_SHIELD_PENETRATION",
        0,//"UNIT_STAT_HEALTH_REGEN",
        0,//"UNIT_STAT_ATTACK_DAMAGE_PERCENT_ADDITIVE",
        0,//"UNIT_STAT_ABILITY_POWER_PERCENT_ADDITIVE",
        0,//"UNIT_STAT_DODGE_NEGATE_PERCENT_ADDITIVE",
        0,//"UNIT_STAT_DEFLECTION_NEGATE_PERCENT_ADDITIVE",
        0,//"UNIT_STAT_ATTACK_CRITICAL_NEGATE_PERCENT_ADDITIVE",
        0,//"UNIT_STAT_ABILITY_CRITICAL_NEGATE_PERCENT_ADDITIVE",
        0,//"UNIT_STAT_DODGE_NEGATE_RATING",
        0,//"UNIT_STAT_DEFLECTION_NEGATE_RATING",
        0,//"UNIT_STAT_ATTACK_CRITICAL_NEGATE_RATING",
        0,//"UNIT_STAT_ABILITY_CRITICAL_NEGATE_RATING",
        0,//"Offense",
        0,//"Defense",
        0,//"UNIT_STAT_DEFENSE_PENETRATION",
        0,//"UNIT_STAT_EVASION_RATING",
        0,//"UNIT_STAT_CRITICAL_RATING",
        0,//"UNIT_STAT_EVASION_NEGATE_RATING",
        0,//"UNIT_STAT_CRITICAL_NEGATE_RATING",
        0,//"Offense %",
        0,//"Defense %",
        0,//"UNIT_STAT_DEFENSE_PENETRATION_PERCENT_ADDITIVE",
        0,//"UNIT_STAT_EVASION_PERCENT_ADDITIVE",
        0,//"Accuracy",
        0,//"Critical Chance",
        0,//"Critical Avoidance",
        0,//"Health %",
        0,//"Protection %",
        0,//"Speed %",// "UNIT_STAT_SPEED_PERCENT_ADDITIVE",
        0,//"UNIT_STAT_COUNTER_ATTACK_RATING",
        0,//"UNIT_STAT_TAUNT"
    ]
