'use strict'
module.exports = [
        "None",
        "Health",
        "Strength",
        "Agility",
        "Intelligence",
        "Speed",
        "Physical Damage",
        "Special Damage", //"UNIT_STAT_ABILITY_POWER",
        "Armor", //"UNIT_STAT_ARMOR",
        "Resistance", //"UNIT_STAT_SUPPRESSION",
        "Armor Penetration", //"UNIT_STAT_ARMOR_PENETRATION",
        "Resistance Penetration", //"UNIT_STAT_SUPPRESSION_PENETRATION",
        "Dodge Rating", //"UNIT_STAT_DODGE_RATING",
        "Deflection Rating", //"UNIT_STAT_DEFLECTION_RATING",
        "Physical Critical Rating", //"UNIT_STAT_ATTACK_CRITICAL_RATING",
        "Special Critical Rating", //"UNIT_STAT_ABILITY_CRITICAL_RATING",
        "Critical Damage",
        "Potency",
        "Tenacity",
        "UNIT_STAT_DODGE_PERCENT_ADDITIVE",
        "UNIT_STAT_DEFLECTION_PERCENT_ADDITIVE",
        "Physical Critical Chance", //"UNIT_STAT_ATTACK_CRITICAL_PERCENT_ADDITIVE",
        "Special Critical Chance", //"UNIT_STAT_ABILITY_CRITICAL_PERCENT_ADDITIVE",
        "Armor",
        "Resistance",
        "Armor Penetration",
        "Resistance Penetration",
        "Health Steal",//"UNIT_STAT_HEALTH_STEAL",
        "Protection",
        "UNIT_STAT_SHIELD_PENETRATION",
        "UNIT_STAT_HEALTH_REGEN",
        "UNIT_STAT_ATTACK_DAMAGE_PERCENT_ADDITIVE",
        "UNIT_STAT_ABILITY_POWER_PERCENT_ADDITIVE",
        "UNIT_STAT_DODGE_NEGATE_PERCENT_ADDITIVE",
        "UNIT_STAT_DEFLECTION_NEGATE_PERCENT_ADDITIVE",
        "UNIT_STAT_ATTACK_CRITICAL_NEGATE_PERCENT_ADDITIVE",
        "UNIT_STAT_ABILITY_CRITICAL_NEGATE_PERCENT_ADDITIVE",
        "UNIT_STAT_DODGE_NEGATE_RATING",
        "UNIT_STAT_DEFLECTION_NEGATE_RATING",
        "UNIT_STAT_ATTACK_CRITICAL_NEGATE_RATING",
        "UNIT_STAT_ABILITY_CRITICAL_NEGATE_RATING",
        "Offense",
        "Defense",
        "UNIT_STAT_DEFENSE_PENETRATION",
        "UNIT_STAT_EVASION_RATING",
        "UNIT_STAT_CRITICAL_RATING",
        "UNIT_STAT_EVASION_NEGATE_RATING",
        "UNIT_STAT_CRITICAL_NEGATE_RATING",
        "Offense %",
        "Defense %",
        "UNIT_STAT_DEFENSE_PENETRATION_PERCENT_ADDITIVE",
        "UNIT_STAT_EVASION_PERCENT_ADDITIVE",
        "Accuracy",
        "Critical Chance",
        "Critical Avoidance",
        "Health %",
        "Protection %",
        "Speed %",// "UNIT_STAT_SPEED_PERCENT_ADDITIVE",
        "UNIT_STAT_COUNTER_ATTACK_RATING",
        "UNIT_STAT_TAUNT"
    ]
