'use strict'
const Cmds = {}
const WebHook = require('./webHook')
Cmds.addGuildCmd = require('./addGuildCmd')
Cmds.addGlobalCmd = require('./addGlobalCmd')
Cmds.deleteGuildCmds = require('./deleteGuildCmds')
Cmds.getChannel = require('./getChannel')
Cmds.getGuild = require('./getGuild')
Cmds.getGuildMember = require('./getGuildMember')
Cmds.getMsg = require('./getMsg')
Cmds.getRoles = require('./getRoles')
Cmds.getUser = require('./getUser')
Cmds.editMsg = require('./editMsg')
Cmds.getGlobalCmds = require('./getGlobalCmds')
Cmds.getGuildCmds = require('./getGuildCmds')
Cmds.RESTHandler = require('./discordFetch')
Cmds.sendDM = require('./sendDM')
Cmds.sendMsg = require('./sendMsg')
Cmds.webHookFile = WebHook.File
Cmds.webHookMsg = WebHook.Msg
module.exports = Cmds
