'use strict'
const Cmds = {}

Cmds.adminNotAuth = require('./adminNotAuth')
Cmds.addShardCmds = require('./addShardCmds')
Cmds.arrayToObject = require('./arrayToObject')

Cmds.botRequest = require('./botRequest')
Cmds.buttonPick = require('./buttonPick')

Cmds.calcFinalStats = require('./calcFinalStats')
Cmds.calcGuildStats = require('./calcGuildStats')
Cmds.calcRosterStats = require('./calcRosterStats')
Cmds.calcUnitStats = require('./calcUnitStats')
Cmds.checkBotOwner = require('./checkBotOwner')
Cmds.checkGuide = require('./checkGuide')
Cmds.checkGuildAdmin = require('./checkGuildAdmin')
Cmds.checkRaid = require('./checkRaid')
Cmds.checkServerAdmin = require('./checkServerAdmin')
Cmds.checkShardAdmin = require('./checkShardAdmin')
Cmds.checkSuperAdmin = require('./checkSuperAdmin')
Cmds.checkUnitMats = require('./checkUnitMats')
Cmds.confirmButton = require('./confirmButton')
Cmds.createIntialMessage = require('./createIntialMessage')

Cmds.dbProjection = require('./dbProjection')

Cmds.editUnit = require('./editUnit')
Cmds.enum = require('./enum')
Cmds.enumPerms = require('./enumPerms')
Cmds.enumUnitInfo = require('./enumUnitInfo')

Cmds.fetchGuild = require('./fetchGuild')
Cmds.fetchPlayer = require('./fetchPlayer')
Cmds.findFaction = require('./findFaction')
Cmds.findUnit = require('./findUnit')

Cmds.getAbilityDmg = require('./getAbilityDmg')
Cmds.getAbilityType = require('./getAbilityType')
Cmds.getDiscordAC = require('./getDiscordAC')
Cmds.getFakeUnit = require('./getFakeUnit')
Cmds.getFaction = require('./getFaction')
Cmds.getFactionUnits = require('./getFactionUnits')
Cmds.getGearParts = require('./getGearParts')
Cmds.getGuildId = require('./getGuildId')
Cmds.getGuildName = require('./getGuildName')
Cmds.getGuildMemberName = require('./getGuildMemberName')
Cmds.getGuildShardId = require('./getGuildShardId')
Cmds.getLowTickets = require('./getLowTickets')
Cmds.getImg = require('./getImg')
Cmds.getOffenseStat = require('./getOffenseStat')
Cmds.getPayouts = require('./getPayouts')
Cmds.getPlayerOrder = require('./getPlayerOrder')
Cmds.getPOHour = require('./getPOHour')
Cmds.getNeededGear = require('./getNeededGear')
Cmds.getNeededRelicMats = require('./getNeededRelicMats')
Cmds.getOptValue = require('./getOptValue')
Cmds.getPlayerAC = require('./getPlayerAC')
Cmds.getPlayerId = require('./getPlayerId')
Cmds.getRanks = require('./getRanks')
Cmds.getRotation = require('./getRotation')
Cmds.getRole = require('./getRole')
Cmds.getScreenShot = require('./getScreenShot')
Cmds.getShard = require('./getShard')
Cmds.getShardName = require('./getShardName')
Cmds.getTopUnits = require('./getTopUnits')
Cmds.getWebUnitStats = require('./getWebUnitStats')
Cmds.getRole = require('./getRole')
Cmds.getTBInfo = require('./getTBInfo')
Cmds.getUnit = require('./getUnit')
Cmds.getUnitName = require('./getUnitName')
Cmds.getUnitStats = require('./getUnitStats')
Cmds.guildReport = require('./guildReport')

Cmds.joinImages = require('./joinImages')

Cmds.manageReportUnits = require('./manageReportUnits')
Cmds.modifyUnit = require('./modifyUnit')
Cmds.notifyBotOwner = require('./notifyBotOwner')

Cmds.removeShardCmds = require('./removeShardCmds')
Cmds.replyButton = require('./replyButton')
Cmds.replyComponent = require('./replyComponent')
Cmds.replyError = require('./replyError')
Cmds.replyMsg = require('./replyMsg')
Cmds.replyTokenError = require('./replyTokenError')
Cmds.responseMsg = require('./responseMsg')

Cmds.sendMsg = require('./sendMsg')
Cmds.sendMessages = require('./sendMessages')
Cmds.showRotationSchedule = require('./showRotationSchedule')
Cmds.squads = require('./squads')

Cmd.timeTillPayout = require('./timeTillPayout')
Cmds.truncateString = require('./truncateString')
module.exports = Cmds
